name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: nnn

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: false

    - name: Fix Corrupt Wrapper
      run: |
        rm -f gradle/wrapper/gradle-wrapper.jar
        gradle wrapper --gradle-version 9.3.1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Decode Keystore
      run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > app/release.jks

    - name: Build Optimized Release APK
      run: ./gradlew assembleRelease
      env:
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    - name: Generate Temporary Download Link
      run: |
        APK_FILE=$(ls app/build/outputs/apk/release/*.apk | head -n 1)
        echo "Uploading $APK_FILE to bashupload.com..."
        curl https://bashupload.com/$(basename $APK_FILE) --data-binary @"$APK_FILE" > download_url.txt
        echo "------------------------------------------------"
        echo "DOWNLOAD LINK: $(cat download_url.txt)"
        echo "------------------------------------------------"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Fast-Release-APK
        path: app/build/outputs/apk/release/*.apk
        retention-days: 1
